CREATE TABLE polls (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR UNIQUE NOT NULL,
  status VARCHAR NOT NULL,
  started_at VARCHAR,
  concluded_at VARCHAR
);

CREATE TABLE items (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE proposals (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  poll_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
	FOREIGN KEY(poll_id) REFERENCES poll(id),
	FOREIGN KEY(item_id) REFERENCES item(id)
);

CREATE TABLE votes (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  voter_id INTEGER NOT NULL,
  proposal_id INTEGER NOT NULL,
  weight INTEGER NOT NULL,
	FOREIGN KEY(voter_id) REFERENCES voter(id),
	FOREIGN KEY(proposal_id) REFERENCES proposal(id)
);

CREATE TABLE voters (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR UNIQUE NOT NULL,
  slack_id VARCHAR
);
